// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.API.Data;

#nullable disable

namespace Notes.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522110946_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notes.API.Models.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f5c3a1e-8c6c-4b3a-9a29-aaa1dcb6fd01"),
                            Description = "Discussion points from the weekly team meeting.",
                            IsVisible = true,
                            Title = "Meeting Notes"
                        },
                        new
                        {
                            Id = new Guid("5a02d8de-2320-4be2-a041-5629d0b44f7e"),
                            Description = "Milk, Eggs, Bread, Butter",
                            IsVisible = true,
                            Title = "Shopping List"
                        },
                        new
                        {
                            Id = new Guid("7bb08c4d-4d49-4c13-8a5b-d1c84c2b8a8f"),
                            Description = "Monday: Chest, Tuesday: Back, Wednesday: Legs",
                            IsVisible = false,
                            Title = "Workout Plan"
                        },
                        new
                        {
                            Id = new Guid("8f0b6fc7-cf8f-47d5-a47c-2a463c0896a1"),
                            Description = "AI Chatbot, Weather App, Budget Tracker",
                            IsVisible = true,
                            Title = "Project Ideas"
                        },
                        new
                        {
                            Id = new Guid("d4b0b244-7296-4c76-a18e-d1c3f406f3ef"),
                            Description = "Clean Code, The Pragmatic Programmer, Atomic Habits",
                            IsVisible = false,
                            Title = "Reading List"
                        },
                        new
                        {
                            Id = new Guid("b95f03a4-5d90-4b0e-82eb-3d05c2c0dd61"),
                            Description = "Visit Spain in August. Book flights and hotels.",
                            IsVisible = true,
                            Title = "Holiday Plans"
                        },
                        new
                        {
                            Id = new Guid("9bd5f5b1-80f5-4c5b-b8aa-ff2d90eab5f5"),
                            Description = "Login button not responsive on mobile devices.",
                            IsVisible = true,
                            Title = "Bug Report"
                        },
                        new
                        {
                            Id = new Guid("d68fa42e-e5b7-4f0a-b2c2-0bc66e4094f9"),
                            Description = "Watch, Wallet, Personalized Mug",
                            IsVisible = false,
                            Title = "Birthday Gift Ideas"
                        },
                        new
                        {
                            Id = new Guid("ee682960-978d-4ea3-bdd2-7d08c999e0f7"),
                            Description = "Chocolate cake with extra cocoa and vanilla.",
                            IsVisible = true,
                            Title = "Recipe Notes"
                        },
                        new
                        {
                            Id = new Guid("7aa0e9df-2a2d-4eaf-aaf1-6355be3cb431"),
                            Description = "Summarized notes from 'Deep Work' by Cal Newport.",
                            IsVisible = true,
                            Title = "Book Summary"
                        },
                        new
                        {
                            Id = new Guid("e0d9f190-b80e-4e59-b7a7-2c46045c48f1"),
                            Description = "Reflections and highlights of the day.",
                            IsVisible = false,
                            Title = "Daily Journal"
                        },
                        new
                        {
                            Id = new Guid("c6b201a4-2b2c-42f3-a0d6-e5f8d045d281"),
                            Description = "Learn Docker, Read 12 books, Run a marathon.",
                            IsVisible = true,
                            Title = "Goals for 2025"
                        },
                        new
                        {
                            Id = new Guid("fb1f1746-84d8-4ef3-8a33-9c7f0c0c4189"),
                            Description = "Submit monthly report, Check emails, Attend sync call.",
                            IsVisible = true,
                            Title = "Work Reminders"
                        },
                        new
                        {
                            Id = new Guid("ae9b3a75-5f3b-4f08-b1e4-b8e6b7f93e35"),
                            Description = "Tutorial on ASP.NET Core, React intro video",
                            IsVisible = false,
                            Title = "Ideas for YouTube"
                        },
                        new
                        {
                            Id = new Guid("617f6f94-86b3-4092-8a75-2391fc6cb5fc"),
                            Description = "Clothes, Charger, Toothbrush, Travel documents",
                            IsVisible = true,
                            Title = "Packing List"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
